name       : protonmail-bridge
version    : 3.3.2
release    : 13
source     :
    - git|https://github.com/ProtonMail/proton-bridge : v3.3.2
license    : GPL-3.0-or-later
component  : network.mail
summary    : ProtonMail Bridge for e-mail clients.
description: |
    ProtonMail Bridge enables the integration of ProtonMail accounts with email clients through local IMAP/SMTP servers.
networking : true
builddeps  :
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandCompositor)
    - pkgconfig(Qt6Widgets)
    - pkgconfig(grpc)
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
    - pkgconfig(libsecret-1)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - git
    - golang
setup      : |
    %patch -p1 -i $pkgfiles/0001-fix-build.patch
build      : |
    export VCPKG_OVERLAY_PORTS=$pkgfiles/overlays
    make build
install    : |
    install -D cmd/Desktop-Bridge/deploy/linux/proton-bridge $installdir/usr/bin/proton-bridge
    install -D cmd/Desktop-Bridge/deploy/linux/bridge-gui $installdir/usr/bin/proton-bridge-gui
    install -D cmd/Desktop-Bridge/deploy/linux/protonmail-bridge $installdir/usr/bin/protonmail-bridge
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/proton-bridge.desktop $installdir/usr/share/applications/protonmail-bridge.desktop
