name       : protonmail-bridge
version    : 2.1.3
release    : 10
source     :
    - https://github.com/ProtonMail/proton-bridge/archive/refs/tags/br-2.1.3.tar.gz : c2736fec4d0b491aef624692423ba3d7274f63ccd515a59e281aed1d71e776f3
license    : GPL-3.0-or-later
component  : network.mail
summary    : ProtonMail Bridge for e-mail clients.
description: |
    ProtonMail Bridge enables the integration of ProtonMail accounts with email clients through local IMAP/SMTP servers.
networking : true
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(libsecret-1)
    - git
    - golang
rundeps    :
    - gnome-keyring
    - qt5-quickcontrols
build      : |
    export PATH=$PATH:$(go env GOPATH)/bin/
    export QT_PKG_CONFIG=true
    export APP=bridge
    %make build
    %make build-launcher
install    : |
    install -D cmd/Desktop-Bridge/deploy/linux/proton-bridge $installdir/usr/bin/proton-bridge
    install -D launcher-proton-bridge $installdir/usr/bin/protonmail-bridge
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
    install -Dm00644 dist/proton-bridge.desktop $installdir/usr/share/applications/protonmail-bridge.desktop
