name       : protonmail-bridge
version    : 1.5.7
release    : 2
source     :
    - https://github.com/ProtonMail/proton-bridge/archive/br-1.5.7.tar.gz : c725971e7daf4cc59150d7cece4b324719b88dd463596e781022e50b3bb8f597
license    : GPL-3.0-or-later
component  : network.mail
summary    : ProtonMail Bridge for e-mail clients.
description: ProtonMail Bridge enables the integration of ProtonMail accounts with email clients through local IMAP/SMTP servers.
networking : true
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libsecret-1)
    - git
    - golang
rundeps    :
    - gnome-keyring
    - qt5-quickcontrols2
build      : |
    export PATH=$PATH:$(go env GOPATH)/bin/
    export QT_PKG_CONFIG=true
    %make
install    : |
    install -D cmd/Desktop-Bridge/deploy/linux/proton-bridge $installdir/usr/bin/protonmail-bridge
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
    install -Dm00644 $pkgfiles/protonmail-bridge.desktop $installdir/usr/share/applications/protonmail-bridge.desktop
