name       : protonmail-bridge
version    : 2.2.2
release    : 12
source     :
    - https://github.com/ProtonMail/proton-bridge/archive/refs/tags/v2.2.2.tar.gz : 3b53834cbe730547472e936a300cf5124ff97789eeb07d3961aa5a43480f28af
license    : GPL-3.0-or-later
component  : network.mail
summary    : ProtonMail Bridge for e-mail clients.
description: |
    ProtonMail Bridge enables the integration of ProtonMail accounts with email clients through local IMAP/SMTP servers.
networking : true
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(libsecret-1)
    - git
    - golang
rundeps    :
    - qt5-quickcontrols
build      : |
    export PATH=$PATH:$(go env GOPATH)/bin/
    export QT_PKG_CONFIG=true
    export APP=bridge
    %make build
    %make build-launcher
install    : |
    install -D cmd/Desktop-Bridge/deploy/linux/proton-bridge $installdir/usr/bin/proton-bridge
    install -D launcher-proton-bridge $installdir/usr/bin/protonmail-bridge
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
    install -Dm00644 dist/proton-bridge.desktop $installdir/usr/share/applications/protonmail-bridge.desktop
