name       : protonmail-bridge
version    : 1.8.10
release    : 8
source     :
    - https://github.com/ProtonMail/proton-bridge/archive/refs/tags/v1.8.10.tar.gz : efa2abc6390ea6f18a4f2472533722b6bbd4b76f450553df5215167642022595
license    : GPL-3.0-or-later
component  : network.mail
summary    : ProtonMail Bridge for e-mail clients.
description: |
    ProtonMail Bridge enables the integration of ProtonMail accounts with email clients through local IMAP/SMTP servers.
networking : true
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Qml)
    - pkgconfig(libsecret-1)
    - git
    - golang
rundeps    :
    - gnome-keyring
    - qt5-graphicaleffects
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-go.sum.patch
build      : |
    export PATH=$PATH:$(go env GOPATH)/bin/
    export QT_PKG_CONFIG=true
    export APP=bridge
    %make build
    %make build-launcher
install    : |
    install -D cmd/Desktop-Bridge/deploy/linux/proton-bridge $installdir/usr/bin/proton-bridge
    install -D launcher-proton-bridge $installdir/usr/bin/protonmail-bridge
    install -Dm00644 cmd/Desktop-Bridge/deploy/linux/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
    install -Dm00644 dist/proton-bridge.desktop $installdir/usr/share/applications/protonmail-bridge.desktop
